version: "3.8"

services:
  my_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7878"
    deploy:
      replicas: 4
    environment:
      - PING_LISTEN_PORT=0.0.0.0:7878

  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:8080
    depends_on:
      - my_app
